# Generated by Django 4.1.5 on 2023-06-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='shop',
            new_name='organization',
        ),
    ]
