# Generated by Django 4.1.5 on 2023-06-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_product_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shop',
            new_name='organization',
        ),
    ]
